test/CMakeLists.txt: move 'APPEND rgw_libs Boost::filesystem' to top level
Without this, the ceph-test package fails to build on openSUSE Tumbleweed
due to linker errors:

[ 5176s] /usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: /tmp/ccOoYSy4.ltrans109.ltrans.o: in function `rgw::lua::install_packages(DoutPrefixProvider const*, rgw::sal::RGWRadosStore*, optional_yield, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
[ 5176s] /home/abuild/rpmbuild/BUILD/ceph-16.2.11-57-g9be7fb44a33/build/boost/include/boost/filesystem/path.hpp:807: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
[ 5176s] /usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: /tmp/ccOoYSy4.ltrans109.ltrans.o: in function `rgw::lua::install_packages(DoutPrefixProvider const*, rgw::sal::RGWRadosStore*, optional_yield, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
[ 5176s] /home/abuild/rpmbuild/BUILD/ceph-16.2.11-57-g9be7fb44a33/build/boost/include/boost/filesystem/operations.hpp:172: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
[ 5176s] /usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: /tmp/ccOoYSy4.ltrans109.ltrans.o: in function `rgw::lua::add_package(DoutPrefixProvider const*, rgw::sal::RGWRadosStore*, optional_yield, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
[ 5176s] /home/abuild/rpmbuild/BUILD/ceph-16.2.11-57-g9be7fb44a33/build/boost/include/boost/filesystem/path.hpp:807: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
[ 5176s] /usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: /tmp/ccOoYSy4.ltrans109.ltrans.o: in function `rgw::lua::add_package(DoutPrefixProvider const*, rgw::sal::RGWRadosStore*, optional_yield, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
[ 5176s] /home/abuild/rpmbuild/BUILD/ceph-16.2.11-57-g9be7fb44a33/build/boost/include/boost/filesystem/operations.hpp:172: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
[ 5186s] collect2: error: ld returned 1 exit status
[ 5186s] make[2]: *** [src/test/CMakeFiles/ceph_test_cls_rgw_log.dir/build.make:148: bin/ceph_test_cls_rgw_log] Error 1
[ 5186s] make[1]: *** [CMakeFiles/Makefile2:10001: src/test/CMakeFiles/ceph_test_cls_rgw_log.dir/all] Error 2

Signed-off-by: Tim Serong <tserong@suse.com>